# handlers file for ubuntu-2004-apache-mod-php
---
- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: reload apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded
